### ISSUE TITLE
[BUG]: After installing this this extension I get the following error on startup of A1111

### ISSUE THREAD

**Issue by Nrgte** [wywywywy/sd-webui-depth-lib#10]
Hi

This is the error I receive on startup.

`
To create a public link, set `share=True` in `launch()`.
Startup time: 27.3s (launcher: 15.9s, import torch: 3.1s, import gradio: 0.8s, setup paths: 0.7s, other imports: 1.8s, list SD models: 0.2s, load scripts: 3.2s, create ui: 1.1s, gradio launch: 0.3s).
*** API error: GET: http://127.0.0.1:7860/info {'error': 'KeyError', 'detail': '', 'body': '', 'errors': "'dataset'"}
    Traceback (most recent call last):
      File "F:\Projects\Stable Diffusion\stable-diffusion-webui\venv\lib\site-packages\anyio\streams\memory.py", line 98, in receive
        return self.receive_nowait()
      File "F:\Projects\Stable Diffusion\stable-diffusion-webui\venv\lib\site-packages\anyio\streams\memory.py", line 93, in receive_nowait
        raise WouldBlock
    anyio.WouldBlock

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "F:\Projects\Stable Diffusion\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\base.py", line 78, in call_next
        message = await recv_stream.receive()
      File "F:\Projects\Stable Diffusion\stable-diffusion-webui\venv\lib\site-packages\anyio\streams\memory.py", line 118, in receive
        raise EndOfStream
    anyio.EndOfStream

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "F:\Projects\Stable Diffusion\stable-diffusion-webui\modules\api\api.py", line 152, in exception_handling
        return await call_next(request)
      File "F:\Projects\Stable Diffusion\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\base.py", line 84, in call_next
        raise app_exc
      File "F:\Projects\Stable Diffusion\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\base.py", line 70, in coro
        await self.app(scope, receive_or_disconnect, send_no_error)
      File "F:\Projects\Stable Diffusion\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\base.py", line 108, in __call__
        response = await self.dispatch_func(request, call_next)
      File "F:\Projects\Stable Diffusion\stable-diffusion-webui\modules\api\api.py", line 116, in log_and_time
        res: Response = await call_next(req)
      File "F:\Projects\Stable Diffusion\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\base.py", line 84, in call_next
        raise app_exc
      File "F:\Projects\Stable Diffusion\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\base.py", line 70, in coro
        await self.app(scope, receive_or_disconnect, send_no_error)
      File "F:\Projects\Stable Diffusion\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\cors.py", line 84, in __call__
        await self.app(scope, receive, send)
      File "F:\Projects\Stable Diffusion\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\gzip.py", line 24, in __call__
        await responder(scope, receive, send)
      File "F:\Projects\Stable Diffusion\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\gzip.py", line 44, in __call__
        await self.app(scope, receive, self.send_with_gzip)
      File "F:\Projects\Stable Diffusion\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
        raise exc
      File "F:\Projects\Stable Diffusion\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
        await self.app(scope, receive, sender)
      File "F:\Projects\Stable Diffusion\stable-diffusion-webui\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
        raise e
      File "F:\Projects\Stable Diffusion\stable-diffusion-webui\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
        await self.app(scope, receive, send)
      File "F:\Projects\Stable Diffusion\stable-diffusion-webui\venv\lib\site-packages\starlette\routing.py", line 718, in __call__
        await route.handle(scope, receive, send)
      File "F:\Projects\Stable Diffusion\stable-diffusion-webui\venv\lib\site-packages\starlette\routing.py", line 276, in handle
        await self.app(scope, receive, send)
      File "F:\Projects\Stable Diffusion\stable-diffusion-webui\venv\lib\site-packages\starlette\routing.py", line 66, in app
        response = await func(request)
      File "F:\Projects\Stable Diffusion\stable-diffusion-webui\venv\lib\site-packages\fastapi\routing.py", line 237, in app
        raw_response = await run_endpoint_function(
      File "F:\Projects\Stable Diffusion\stable-diffusion-webui\venv\lib\site-packages\fastapi\routing.py", line 165, in run_endpoint_function
        return await run_in_threadpool(dependant.call, **values)
      File "F:\Projects\Stable Diffusion\stable-diffusion-webui\venv\lib\site-packages\starlette\concurrency.py", line 41, in run_in_threadpool
        return await anyio.to_thread.run_sync(func, *args)
      File "F:\Projects\Stable Diffusion\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
        return await get_asynclib().run_sync_in_worker_thread(
      File "F:\Projects\Stable Diffusion\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
        return await future
      File "F:\Projects\Stable Diffusion\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
        result = context.run(func, *args)
      File "F:\Projects\Stable Diffusion\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 271, in api_info
        return gradio.blocks.get_api_info(config, serialize)  # type: ignore
      File "F:\Projects\Stable Diffusion\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 504, in get_api_info
        serializer = serializing.COMPONENT_MAPPING[type]()
    KeyError: 'dataset'

---
`

A1111 version is v1.5.1

Thanks!

**Comment by wywywywy** [comment]
Hi. 

v1.5.1 is quite old. Can you upgrade to v1.6.0 and try again?

If not then you may have to try an older version of this plugin.

**Comment by Nrgte** [comment]
v1.6.0 has other compatibility issues unfortunatelly. Is there an older commit or version you recommend?

Unfortunatelly there are no tags.

**Comment by wywywywy** [comment]
Perhaps we could try the original repo https://github.com/jexom/sd-webui-depth-lib

It's frozen in time and it was working when everyone was on v1.5.0.

**Comment by Nrgte** [comment]
Unfortuantelly that one crashes too. :(
