### ISSUE TITLE
Depth Lib Tab not showing in the UI

### ISSUE THREAD

**Issue by JakeC418** [wywywywy/sd-webui-depth-lib#12]
**Describe the bug**
The Depth lib tab wont show up after following the installation process.
I already have tried to: 
- reinstall
- restart pc
- reload UI
- restart stable diffusion

**Environment**
Put x in the brackets to select
- [x] Local desktop
- [ ] Colab

**To Reproduce**
1. Open the "Extensions" tab
2. Click on "Install from URL"
3. In "URL for extension's git repository" enter this extension, https://github.com/wywywywy/sd-webui-depth-lib.git
4. Click "Install"
5. Restart WebUI

**Error**

Error executing callback ui_tabs_callback for C:\ai\stable-diffusion-webui\extensions\sd-webui-depth-lib\scripts\main.py
    Traceback (most recent call last):
      File "C:\ai\stable-diffusion-webui\modules\script_callbacks.py", line 166, in ui_tabs_callback
        res += c.callback() or []
      File "C:\ai\stable-diffusion-webui\extensions\sd-webui-depth-lib\scripts\main.py", line 41, in on_ui_tabs
        dataset = gr.Examples(examples=os.path.join(maps_path, t), inputs=[png_input_area], examples_per_page=24, label=None, elem_id="depth_lib_examples")
      File "C:\ai\stable-diffusion-webui\venv\lib\site-packages\gradio\helpers.py", line 58, in create_examples
        examples_obj = Examples(
      File "C:\ai\stable-diffusion-webui\venv\lib\site-packages\gradio\helpers.py", line 209, in __init__
        self.processed_examples = [
      File "C:\ai\stable-diffusion-webui\venv\lib\site-packages\gradio\helpers.py", line 210, in <listcomp>
        [
      File "C:\ai\stable-diffusion-webui\venv\lib\site-packages\gradio\helpers.py", line 211, in <listcomp>
        component.postprocess(sample)
      File "C:\ai\stable-diffusion-webui\venv\lib\site-packages\gradio\components\image.py", line 318, in postprocess
        return client_utils.encode_url_or_file_to_base64(y)
      File "C:\ai\stable-diffusion-webui\venv\lib\site-packages\gradio_client\utils.py", line 387, in encode_url_or_file_to_base64
        return encode_file_to_base64(path)
      File "C:\ai\stable-diffusion-webui\venv\lib\site-packages\gradio_client\utils.py", line 360, in encode_file_to_base64
        with open(f, "rb") as file:
    PermissionError: [Errno 13] Permission denied: 'sd-webui-depth-lib'

**Comment by wywywywy** [comment]
What version of web UI are you using? What do you have under the `extensions\sd-webui-depth-lib\maps' folder?

**Comment by wywywywy** [comment]
I just released a new version #13 can you give it a try

**Comment by JakeC418** [comment]
Thanks it is working now.
